### ISSUE TITLE
Lots and Lots

### ISSUE THREAD

**Issue by phantom-factotum** [soachishti/dislocker-gui#1]
Hey, I am a newbie Linux and all and I have my PC split into 3 partitions: my Ubuntu, Windows, and a partition for files that both will access.  I have both my Windows and File partition encrypted with Bitlocker which led to me discovering dislocker and wishing for a GUI, and thus, finding your project.

The first few issues I encountered all were purely about modules and dependencies. In your README.md the only dependency mentioned is dislocker. As of now, python-tk and psutils (I installed using pip which would mean installing python-pip) are needed.

Next was a small issue about tkinter. For Python versions under 3, the module is named Tkinter. And finally and most importantly, I noticed that your script doesnt detect bitlocker drives that are partitioned on the hard drive

**Comment by soachishti** [comment]
Hi, I am glad that you find the repo useful.

This was an attempt I made to get Windows like prompt for password when Bitlocker drive is detected as it was tedious to execute commands: (https://askubuntu.com/a/617989).

You will need python3, pip3, tkinter, psutil and dislocker (in system path) to get the code up and running. 

I tested this code with my single partition based on the results (logs) of dislocker which I think are different for you. 

The whole logic lies in the `def run(self)` method, there is infinite loop in which `get_unmounted_disks()` is called which return disks which are unmounted and Bitlocker disks (based on dislocker log). Then it asks for password using `passwordDialog(device)` (tkinter) and then finally mount the disk and this loop continues forever with 3 seconds timeout.

```
def run(self):
   while True:    
        devices = d.get_unmounted_disks()
        if len(devices) != 0:
            device = devices[0]
            password = self.passwordDialog(device)
            d.mount(device, password)
        sleep(3000)
```

To get this code running for your partition you will have to tweak for your system, as it wasn't actively developed after initial commits.
